import { Metadata } from 'next/types'

export const metadata: Metadata = {
  title: 'Elias Chane',
  description: 'Generated by create next app',
}

export default function StudioLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="pt-50 bg-white relative">
      <div>{children}</div>
    </main>
  )
}
